[package]
name = "mtransaction"
version = "0.2.2"
edition = "2021"

[[bin]]
name = "mtx-server"
path = "server/main.rs"

[[bin]]
name = "mtx-client"
path = "client/main.rs"

[dependencies]
lazy_static = "1.4.0"
openssl = { version = "0.10" }
jwt = { version = "0.16.0", features = ["openssl"]}
async-stream = "0.3"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
prost = "0.11"
tokio = { version = "1.36", features = [ "rt-multi-thread", "time", "fs", "macros", "net",] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.8.3", features = ["tls", "gzip"] }
tower = { version = "0.4" }
h2 = "0.3"
log = "0.4.21"
env_logger = "0.9.3"
jsonrpc-core-client = "18.0.0"
jsonrpc-core = "18.0.0"
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
rand = "0.8.5"
structopt = "0.3.26"
solana-sdk = "1.18.7"
solana-client = "1.18.7"
solana-transaction-status = "1.18.7"
x509-parser = "0.14.0"
prometheus = "0.13.3"
warp = "0.3"
base64 = "0.13.1"
bincode = "1.3.3"
enum_dispatch = "0.3.12"
memory-stats = "1.1.0"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
signal-hook = "0.3.17"

[build-dependencies]
tonic-build = { version = "0.8.4", features = ["prost"] }
